<?php
/**
 * Copyright © 2015 RokanThemes.com. All rights reserved.

 * @author RokanThemes Team <contact@rokanthemes.com>
 */
?>
<?php
/**
 * Blog related posts template
 *
 * @var $block \Rokanthemes\Blog\Block\Post\View\RelatedPosts
 */
  $_post = $this->getPost();
?>

<?php if ($block->displayPosts()) { ?>
    <?php $_postCollection = $block->getPostCollection(); ?>
    <?php if ($_postCollection->count()) { ?>
    <div class="block related">
        <div class="block-title title">
            <h2 id="block-relatedposts-heading" role="heading" aria-level="2">
                <?php echo __('You Might Also Like') ?>
            </h2>
        </div>
        <ol class="block-content">
            <?php foreach ($_postCollection as $_post) { ?>
                <li class="item">	
                    <a class="post-item-link"
                       href="<?php echo $_post->getPostUrl() ?>">
                        <?php echo $block->escapeHtml($_post->getTitle()); ?>
                    </a>
                </li>
            <?php } ?>
        </ol>
    </div>
	
    <?php } ?>
<?php } ?>