<div class="top-content-home">
	<div class="banner-top-home home2">
		<!-- <div class="container">
			<?php //echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('banner_top')->toHtml();?>
		</div> -->
	</div>
	<div class="best-sale">
		<div class="box-full">
			<?php echo $block->getLayout()->createBlock('Rokanthemes\BestsellerProduct\Block\Bestseller')->setTemplate('Rokanthemes_BestsellerProduct::bestseller.phtml')->toHtml();?> 
		</div>
	</div>
	<div class="banner-middle">
		<?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('banner_middle')->toHtml();?>
	</div>
</div>
