<div class="header-container">
	<div class="header">
		<div class="container">
			<div class="for-full-withmenu">
				<div class="row">
					<div class="col-md-9 col-sm-9 col-xs-7 col-logo">
						<?php echo $this->getChildHtml("logo"); ?>
						<?php echo $this->getChildHtml("top.navigation.sections"); ?>	
					</div>
					<div class="col-md-3 col-sm-3 col-xs-5 col-menu">
						<div class="header-top-setting pull-right">
							<a href="#" class="actions-top"><i class="ion ion-navicon"> </i></a>
							<div class="setting-container">
								<h3><?php echo __('My Account') ?></h3>
								<?php if(!$this->helper('Rokanthemes\Themeoption\Helper\Data')->isLoggedIn()){?>
													<a href="<?php echo $this->helper('Rokanthemes\Themeoption\Helper\Data')->getBaseUrl('customer/account/login/');?>"><?php echo __('Log in');?></a>
												<?php
												}
												else{
												?>	
												<a href="<?php echo $this->helper('Rokanthemes\Themeoption\Helper\Data')->getBaseUrl('customer/account/logout');?>"><?php echo __('Logout');?></a>
												
										<?php } ?>
								<?php echo $this->getChildHtml("top_link"); ?>
								<!-- <h3><?php //echo __('Language') ?></h3> -->
								<?php //echo $this->getChildHtml("store_language"); ?>
								<!-- <h3><?php //echo __('Currency') ?></h3> -->
								<?php //echo $this->getChildHtml("currency"); ?>
							</div>
						</div>					
						<?php echo $this->getChildHtml("minicart");?>
						<?php echo $this->getChildHtml("topSearch"); ?>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

<script type="text/javascript">
    require(['jquery'],function($){
        $(document).ready(function($){
			$(window).scroll(function() {
				var num = $('.header-container').outerHeight();
				var screenWidth = $(window).width();
				
				if ($(this).scrollTop() > num && screenWidth >= 768 ){  
					$(".header").addClass("sticky");
				}
				else{
					$(".header").removeClass("sticky");
				}
			});
		});
    });
</script>
